### ISSUE TITLE
kaggleへsubmitができるようなページを作る

### ISSUE THREAD

**Issue by aShotaSakamoto** [kurama554101/table_analyzer#2]

**Comment by aShotaSakamoto** [comment]
https://qiita.com/uni-3/items/f1fdbeeddd08ca22c80f

ここらへんを参考にする

**Comment by sakamomo554101** [comment]
https://github.com/Kaggle/kaggle-api

上記を見てみる。

**Comment by sakamomo554101** [comment]
https://doarakko.hatenablog.com/entry/kaggle_api_in_python

まぁ、api.pyの実装を見て、呼び出し方を試すしかないな。

**Comment by sakamomo554101** [comment]
http://www.currypurin.com/entry/2018/kaggle-api
http://www.currypurin.com/entry/kaggle-api-submit

**Comment by sakamomo554101** [comment]
https://github.com/Kaggle/kaggle-api/blob/master/kaggle/api/kaggle_api_extended.py#L83

上記見ると、環境変数として、KAGGLE_CONFIG_DIRに値を入れれば良さそう。

**Comment by sakamomo554101** [comment]
#6 で対応中（ほぼ対応できてるので、titanicのsubmitが問題なさそうだったら、マージする）
